<?php

namespace JUMAIN\ChallengeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
    public function findAllClients()
    {
        $clients = $this->getEntityManager()
                        ->createQuery(
                        'SELECT c FROM JUMAINChallengeBundle:Client c ORDER BY c.clientName ASC')
                        ->getResult();

        return $clients;
    }
}
